[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
description = "Quizz"
name = "quizz"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "marimo run quizz.py"
dev = "marimo edit quizz.py"

[dependencies]
python = ">=3.12.5,<4"
marimo = ">=0.8.9,<0.9"
